version: '3.4'
services:
  ########################
  # SERVICE DEPENDENCIES #
  ########################
  nodemock:
    restart: unless-stopped
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    volumes:
      - ./config.json:/app/mock/config.json
    env_file:
      - ./.env
    ports:
      - 3000:3000
    command: bash -c "npm run start"
    networks:
      default:

networks:
  default:
