version: '3.4'
services:
  ########################
  # SERVICE DEPENDENCIES #
  ########################
  zuju-test:
    restart: unless-stopped
    image: ${IMAGE_NAME}:dev
    build: 
      context: ../../
      dockerfile: ./misc/docker/dockerfile
    working_dir: ${PWD}/../..
    volumes:
      - ../../:${PWD}/../..
    env_file:
      - ./.env
    command: bash -c "npm run dev"
    ports:
      - 3000:3000
    networks:
      default:

networks:
  default:
